backend/src/account/urls.py
from django.urls import path, re_path
from django.conf.urls import url, include
from django.conf import settings
from . import views
#from django.contrib.auth.views import login, logout, password_reset, password_reset_done, password_reset_confirm, password_reset_complete
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView, PasswordChangeDoneView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView

app_name = 'account'
urlpatterns = [
    # Accounts
    path('auth/', include('social_django.urls', namespace='social')),
    path('logout/', LogoutView.as_view(template_name='logout.html'), {'next_page': settings.LOGOUT_REDIRECT_URL}, name='logout'),
    path('signup/', views.signup, name='account-signup'),
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    #path('logout/', LogoutView.as_view(template_name='logout.html'), name='logout'),
    path('profile/', views.view_profile, name='view-profile'),
    path('profile/edit/', views.edit_profile, name='edit-profile'),
    # path('change_password/', views.account.change_password, name='change-password'),

    # # Password Reset
    # path('reset_password/', password_reset, {
    #     'template_name': 'accounts/reset_password.html',
    #     'post_reset_redirect': 'accounts:password_reset_done', 
    #     'email_template_name': 'accounts/reset_password_email.html'
    #     }, 
    #     name='reset-password'),

    # path('reset_password/done/', password_reset_done, {
    #     'template_name': 'accounts/reset_password_sent.html'
    #     },
    #     name='password_reset_done'),

    # re_path(r'^reset_password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', password_reset_confirm, {
    #     'post_reset_redirect': 'accounts:password_reset_complete',
    #     'template_name': 'accounts/reset_password_new.html'
    #     }, 
    #     name='password_reset_confirm'),

    # path('reset_password/complete/', password_reset_complete, {
    #     'template_name': 'accounts/reset_password_complete.html'
    #     }, 
    #     name='password_reset_complete'),

    # # Add Details

]

backend/src/api/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

app_name = 'api'

urlpatterns = [
    #path('api/', include('api.urls', namespace='api')),
]

backend/src/leaguely/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
    path('api/', include('api.api.urls')),
    path('account/', include('account.urls', namespace='account')),
    
]

backend/src/account/models.py
from django.db import models
from api.models import *
from django.db.models.signals import post_save

# Managers
class UserProfileManager(models.Manager):

    def get_queryset(self):
        return super(UserProfileManager, self).get_queryset()

# Users
class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='profile_image', blank=True, null=True)
    phone_number = models.CharField(max_length=9, null=True, blank=True)
    address = models.CharField(max_length=240, null=True, blank=True)
    date_of_birth = models.DateField(null=True, blank=True)
    is_admin = models.BooleanField(default=False)
    is_player = models.BooleanField(default=False)
    is_coach = models.BooleanField(default=False)
    is_referee = models.BooleanField(default=False)

    # override objects with manager
    objects = UserProfileManager()

    def __str__(self):
        return self.user.__str__()
    
    def to_string(self):
        return str(self.user.first_name) + " " + str(self.user.last_name)

# Signal to create UserProfile when a new User is created
def create_profile(sender, **kwargs):
    if kwargs['created']:
        user = kwargs['instance']
        user_profile = UserProfile.objects.create(user=user)
        if user.is_staff:
            user_profile.is_admin = True
            user_profile.save()

post_save.connect(create_profile, sender=User)

backend/src/account/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User
from django.db import transaction
from .models import *
from django.forms import ModelForm


class RegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)


    class Meta:
        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2',
        )

    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']

        if commit:
            user.save()

        return User

class EditProfileForm(UserChangeForm):

    class Meta:
        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
            'email',
            'password',
        )

class EditUserProfileForm(ModelForm):

    class Meta:
        model = UserProfile
        fields = ['image', 'date_of_birth']

backend/src/account/views.py
from django.shortcuts import render, HttpResponse
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, PasswordChangeForm, PasswordResetForm
from .forms import RegistrationForm, EditProfileForm, EditUserProfileForm
from .models import UserProfile
from django.contrib.auth.models import User
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.urls import reverse

def signup(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            return HttpResponseRedirect(reverse('account:view-profile', args={'user': user}))
    else:
        form = RegistrationForm()
        args = {'form': form}
        return render(request, 'signup.html', args)

def view_profile(request):
    user = request.user.userprofile
    my_classes = user.class_set.all()
    my_videos = user.video_set.all()
    args = {'user': request.user,
            'my_classes': my_classes,
            'my_videos': my_videos,
            }
    return render(request, 'profile.html', args)

def edit_profile(request):
    if request.method == 'POST':
        form = EditProfileForm(request.POST, instance=request.user)
        form2 = EditUserProfileForm(request.POST, request.FILES, instance=request.user.userprofile)
        if form.is_valid() and form2.is_valid():
            form.save()
            data = form2.cleaned_data
            profile = UserProfile.objects.get(user=request.user)
            profile.image = data['image']
 #           profile.phone_number = data['phone_number']
 #           profile.address = data['address']
            profile.date_of_birth = data['date_of_birth']
            profile.save()
            #return HttpResponseRedirect(reverse('account:view-profile', args={'user': request.user}))
            return HttpResponseRedirect(reverse('account:view-profile'))
    else:
        form = EditProfileForm(instance=request.user)
        form2 = EditUserProfileForm(instance=request.user.userprofile)
        args = {'user': request.user, 'form': form, 'form2': form2}
        return render(request, 'edit_profile.html', args)

def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(data=request.POST, user=request.user)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, request.user)
            return HttpResponseRedirect(reverse('account:view-profile', args={'user': request.user}))
        else:
            return HttpResponseRedirect(reverse('account:change-password', args={'user': request.user}))
    else:
        form = PasswordChangeForm(user=request.user)
        args = {'user': request.user, 'form': form}
        return render(request, 'change_password.html', args)

backend/src/account/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        {% block head %}
            <title>Base</title>
        {% endblock %}
    </head>
    <body>
        {% block body %}

        {% endblock %}
    </body>
</html>

backend/src/account/templates/change_password.html
{% extends 'base.html' %}

{% block head %}

<title>Change Password</title>

{% endblock %}

{% block body %}
<div class="container">
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-primary btn-sm" type="submit">Submit</button>
    </form>
</div>
{% endblock %}

backend/src/account/templates/edit_profile.html
{% extends 'base.html' %}

{% block head %}

<title>Profile</title>

{% endblock %}

{% block body %}
<div class="container">
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        {{ form2.as_p }}
        <button class="btn btn-primary btn-sm" type="submit">Submit</button>
    </form>
</div>
{% endblock %}

backend/src/account/templates/login.html
{% extends 'base.html' %}

{% block head %}
<title>Login</title>
{% endblock %}

{% block body %}
<div class="container">
    <h1>Welcome Back!</h1>
    <a href="{% url 'social:begin' 'google-oauth2' %}">Login with Google</a><br>
    <form method='POST'>
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-primary btn-sm" type="submit">Login</button> or, if you don't already have an account, <a class="btn btn-warning btn-sm" href="{% url 'account:account-signup' %}">Register</a>
    </form>
</div>
{% endblock %}

backend/src/account/templates/logout.html
{% extends 'base.html' %}

{% block head %}
<title>Logout</title>
{% endblock %}

{% block body %}
<div class="container">
    <h1>Logged out.</h1>
    <p>
        You have successfully logged out.
    </p>
</div>
{% endblock %}

backend/src/account/templates/profile.html
{% extends 'base.html' %}

{% load account_extras %}

{% block head %}

<title>Profile</title>

{% endblock %}

{% block body %}
<div class="container">
    <h1>Account</h1>
    <a href="{% url 'account:edit-profile' %}" class="btn btn-outline-primary btn-sm">Edit</a>
    <a href="/accounts/change_password" class="btn btn-outline-primary btn-sm">Change Password</a>
    <a href="/accounts/reset_password" class="btn btn-outline-primary btn-sm">Reset Password</a>
    <a href="{% url 'account:logout' %}" class="btn btn-outline-primary btn-sm">Logout</a>
    <div style="margin-top: 20px">
        <div class="row">
            <div class="col-2">
                {% if user.userprofile.image %}
                <img src="{{ user.userprofile.image.url }}" width="128px" height="128px">
                {% endif %}
            </div>
            <div class="col">
                <h2>{{ user.first_name }} {{ user.last_name }}</h2>
                <h3>{{ user }}</h3>
                <h3>{% if user.email %}{{ user.email }}{% endif %}</h3>
                <h3>{% if user.userprofile.date_of_birth %}{{ user.userprofile.date_of_birth }}{% endif %}</h3>
                <h3>{% if user.userprofile.address %}{{ user.userprofile.address }}{% endif %}</h3>
                <h3>{% if user.userprofile.phone_number %}{{ user.userprofile.phone_number }}{% endif %}</h3>
                {% if user.userprofile.is_admin %}
                <a href="/admin/" class="btn btn-outline-success btn-sm">Admin</a>
                {% endif %}
            </div>
        </div>
        <div class="container">
            <p>My Videos</p>
            <div class="container">
                <div class="row">
                    {% for video in my_videos %}
                    <div class="col">
                    <!-- <h2>{{video.title}}</h2> -->
                    <iframe width="420" height="315" src="{% watch_to_embed video.url %}" allow="autoplay; encrypted-media" allowfullscreen></iframe>
                    </div>
                    <!-- <br/><br/> -->
                    {% endfor %}
                </div>
            </div>
        </div>
        <div class="container">
            <p>My Classes</p>
            {% for class in my_classes %}
            <h2>{{class.name}}</h2>
            {% endfor %}
            <a class="btn btn-primary" href="{% url 'upload:join-class' %}">Join classes</a>
        </div>
    </div>
</div>
{% endblock %}

backend/src/account/templates/reset_password.html
{% extends 'base.html' %}

{% block head %}
<title>Reset Password</title>
{% endblock %}

{% block body %}
<div class="container">
    <h1>Password Reset</h1>
    <p>
        Forgotten your password? Enter your email address below, and we'll email instructions for setting a new one.
    </p>
    <form method='POST'>
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-primary btn-sm" type="submit">Reset Password</button>
    </form>
</div>
{% endblock %}

backend/src/account/templates/reset_password_complete.html
{% extends 'base.html' %}

{% block head %}
<title>Reset Complete</title>
{% endblock %}

{% block body %}
<div class="container">
    <h1>Password Reset Complete</h1>
    <p>
        Your password has been set. You may go ahead and log in now.
    </p>
    <a class="btn btn-primary btn-sm" href="{% url 'accounts:login' %}">Login</a>
</div>
{% endblock %}

backend/src/account/templates/reset_password_email.html
{% load i18n %}{% autoescape off %}
{% blocktrans %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktrans %}
 	
{% trans "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% trans "Your username, in case you've forgotten:" %} {{ user.get_username }}
 	
{% trans "Thanks for using our site!" %}
 	
{% blocktrans %}The {{ site_name }} team{% endblocktrans %}

{% endautoescape %}

backend/src/account/templates/reset_password_new.html
{% extends 'base.html' %}

{% block head %}
<title>Set Password</title>
{% endblock %}

{% block body %}
<div class="container">
    <h1>Enter New Password</h1>
    <p>
        Please enter your new password twice so we can verify you typed it in correctly.
    </p>
    <form method='POST'>
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-primary btn-sm" type="submit">Set Password</button>
    </form>
</div>
{% endblock %}

backend/src/account/templates/reset_password_sent.html
{% extends 'base.html' %}

{% block head %}
<title>Reset Password</title>
{% endblock %}

{% block body %}
<div class="container">
    <h1>Password Reset Sent</h1>
    <p>
        We've emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.

        If you don't receive an email, please make sure you've entered the address you registered with, and check your spam folder.
    </p>
</div>
{% endblock %}

backend/src/account/templates/signup.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
    <h1>Register</h1>
    <h2>Sign up for an account.</h2>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-primary btn-sm" type="submit">Submit</button>
    </form>
</div>
{% endblock %}